#!/bin/sh
set -e; set -u; set -C

# nuOS 0.0.12.999a0 - util/nush
#
# Copyright (c) 2008-2024 Chad Jacob Milios and Crop Circle Systems.
# All rights reserved.
#
# This Source Code Form is subject to the terms of the Simplified BSD License.
# If a copy of the Simplified BSD License was not distributed alongside this file, you can
# obtain one at https://www.freebsd.org/copyright/freebsd-license.html . This software
# project is not affiliated with the FreeBSD Project.
#
# Official updates and community support available at https://nuos.org .
# Professional services available at https://ccsys.com .

NUOS_VER=0.0.12.999a0
NUOS_CODE="$(dirname "$(realpath "$0")")/.."

. "$NUOS_CODE/lib/nu_system.sh"

while getopts cl:q OPT; do case $OPT in
	c) OPT_COMMAND=y;;
	l) push LIBS $OPTARG;;
	q) OPT_QUIET=y;;
esac; done; shift $(($OPTIND-1))

baseos_init ${OPT_QUIET:+-q}
nuos_init ${OPT_QUIET:+-q}

if canhas ${LIBS-}; then
	load_lib $LIBS
fi

if srsly ${OPT_COMMAND-}; then
	eval "$@"
else
	while IFS= read _nush_interactive_line; do
		eval "$_nush_interactive_line"
	done
fi
